site_name: Flutter Documentation
nav:
  - Introdução:
    - História do Flutter: historia.md
    - Instalando o Flutter: instalacao.md
    - Criando seu primeiro app: criando_seu_primeiro_app.md
  - Aplicações: aplicacoes.md
  - Vantagens e Desvantagens: vantagens_desvantagens.md
  - Dispositivos e Novidades: dispositivos_tendencias.md
  - Arquitetura: arquitetura.md
  - Uso do Flutter: uso_flutter.md
  - Conclusão: conclusao.md
theme:
  name: material
  custom_dir: overrides
  copyright: 'Todos os direitos reservados © 2024 Flutter Documentation'
extra_css:
  - css/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables