site_name: Flutter Documentation
nav:
  - Introdução:
    - História do Flutter: historia.md
    - Instalando o Flutter: instalacao.md
    - Iniciando um App Flutter: iniciando_um_app_flutter.md
  - Widgets: widgets.md
  - Arquitetura: arquitetura.md
  - Aplicações: aplicacoes.md
  - Vantagens e Desvantagens: vantagens_desvantagens.md
  - Novidades: novidades.md
  - Conclusão: conclusao.md
theme:
  name: material
  custom_dir: overrides
  copyright: 'Todos os direitos reservados © 2024 Flutter Documentation'
extra_css:
  - css/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables